apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: content-quality-assessment
  name: content-quality-assessment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-quality-assessment
  template:
    metadata:
      labels:
        app: content-quality-assessment
    spec:
      containers:
      - name: content-quality-assessment
        image: pseoul/content-quality-assessment:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cqa-service
  labels:
    app: cqa-service
spec:
  type: LoadBalancer
  selector:
    app: cqa-service
  ports:
  - port: 80
    targetPort: 5000